sudo: false
language: ruby
rvm:
  - 2.6.5
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update --system --no-document --quiet

install:
  - apt-get install libsqlite3-dev
  - bundle install --jobs=3 --retry=3
  - bundle install --jobs=4 --retry=3 --gemfile=spec/integration/rails_6.0.2.1/Gemfile

script:
  - bundle exec rubocop && bundle exec rspec

jobs:
  include:
    - stage: gem release
      if: tag =~ ^v
      rvm: 2.6.0
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        gem: annotate
        on:
          tags: true
          repo: ctran/annotate_models
